# Basic Python

# 1. Split this string

In [ ]:
s = "Hi there Sam!"
s.split()

['Hi', 'there', 'Sam!']

# 2. Use .format() to print the following string.

# Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
print("The diameter of {} is {} kilometers.".format(planet,diameter))

The diameter of Earth is 12742 kilometers.


# 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d

{'k1': [1,
  2,
  3,
  {'tricky': ['oh', 'man', 'inception', {'target': [1, 2, 3, 'hello']}]}]}

In [ ]:
g=d['k1'][3]['tricky'][3]['target'][3]
print(g)

hello


# Numpy

In [ ]:
import numpy as np

# 4.1 Create an array of 10 zeros?
# 4.2 Create an array of 10 fives?

In [ ]:
#An array of 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#An array of 10 fives
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

# or

In [ ]:
a=np.zeros(10)
b=np.ones(10)*5
print("An array of 10 zeros is {}".format(a))
print("An array of 10 fives is {}".format(b))

An array of 10 zeros is [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 fives is [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


# 5. Create an array of all the even integers from 20 to 35

In [ ]:
np.arange(20,35,2,dtype=int)

array([20, 22, 24, 26, 28, 30, 32, 34])

# 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
import numpy as np
e=np.arange(9)
f=e.reshape(3,3)
print("A 3x3 matrix with values ranging from 0 to 8 is given below")
print("{}".format(f))

A 3x3 matrix with values ranging from 0 to 8 is given below
[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 7. Concatinate a and b

# a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
import numpy as pd
a=np.array([1,2,3])
b=np.array([4,5,6])
cc=np.concatenate((a,b),axis=0)
print("Concatination of a and b is {}".format(cc))

Concatination of a and b is [1 2 3 4 5 6]


# Pandas
# 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd
d=np.arange(6).reshape(3,2)
c=['1','2']
r=['1','2','3']
dataframe=pd.DataFrame(data=d,index=r,columns=c)
print("A datafram with 3 rows and 2 columns is given below")
print("{}".format(dataframe))

A datafram with 3 rows and 2 columns is given below
   1  2
1  0  1
2  2  3
3  4  5


# 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
import pandas as pd
pd.date_range(start='1st/jan/2023',end='10th/feb/2023',inclusive='both')

TypeError: ignored

# 10. Create 2D list to DataFrame

# lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df=pd.DataFrame(lists,columns=['S/No','Name','Rollno'])
print(df)

   S/No Name  Rollno
0     1  aaa      22
1     2  bbb      25
2     3  ccc      24
